#!/usr/bin/env python3
"""
Build Aniimo Team Builder data from the public Official Aniimo Wiki.

Primary source:
  https://wiki.aniimo.com/

Secondary reference:
  https://aniidex.com/

This script intentionally stores factual source text and derives only simple
machine-readable tags. Strategic recommendations are generated by the website
from those facts; they are not presented as official game advice.
"""

import json, re, time, sys
from pathlib import Path
from urllib.parse import urljoin, urlparse
import requests
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "aniimo.json"
INDEX_URL = "https://wiki.aniimo.com/"
ANIIDEX = "https://aniidex.com/aniimo/"
HEADERS = {"User-Agent": "AniimoTeamBuilder/1.0 (fan project; data refresh)"}
ELEMENTS = ["holy","light","fire","ice","dark","electric","lightning","grass","water","rock","earth","wind"]
ROLES = ["DPS","Heal","Support","BREAK","REGEN"]
STAT_KEYS = ["HP","BREAK","ATK","M.DEF","P.DEF","REGEN"]

def clean_lines(text):
    out=[]
    for line in text.splitlines():
        line=re.sub(r"\s+"," ",line).strip()
        if not line or line=="Image" or line.startswith("Image:"):
            continue
        out.append(line)
    return out

def canonical_element(s):
    s=s.lower()
    return {"holy":"Light","light":"Light","electric":"Lightning","lightning":"Lightning","rock":"Earth","earth":"Earth",
            "fire":"Fire","ice":"Ice","dark":"Dark","grass":"Grass","water":"Water","wind":"Wind"}.get(s)

def tags_for(text):
    rules = {
      "attack_up": r"increase.*(?:attack|damage)|increases.*damage|increased.*damage",
      "defense_down": r"reduce.*(?:defen|defence)|defense down|defence down|damage taken.*increase",
      "debuff": r"debuff|curse|mark|weakness|reducing.*healing|paraly|silence|stun|freeze|slow",
      "break_support": r"break damage|break.*taken|increases.*break|stagger",
      "heal": r"heal|healing|restores? HP|restore.*HP",
      "regen": r"regen|energy|EP|restor.*energy|reduces? the EP cost",
      "shield": r"shield|damage reduction",
      "control": r"stun|silence|paraly|pull|slow|freeze|immobil",
      "burst": r"massive|heavy|bonus damage|extra damage|ultimate",
      "self_scaling": r"stack|stacking|each hit|critical",
    }
    found=[]
    for tag,pat in rules.items():
        if re.search(pat,text,re.I): found.append(tag)
    for el in ["Fire","Water","Grass","Lightning","Earth","Wind","Dark","Ice","Light"]:
        if re.search(el+r"\s+(?:damage|debuff)",text,re.I):
            found.append(el.lower()+"_synergy")
    return sorted(set(found))

def get(url):
    r=requests.get(url,headers=HEADERS,timeout=30)
    r.raise_for_status()
    return r.text

def parse_item(url, fallback_name=None, fallback_number=None):
    html=get(url)
    soup=BeautifulSoup(html,"html.parser")
    text=soup.get_text("\n")
    lines=clean_lines(text)

    # Name and number.
    number=fallback_number
    name=fallback_name
    for i,line in enumerate(lines[:30]):
        m=re.search(r"NO\.\s*(\d+)",line,re.I)
        if m: number=int(m.group(1))
    if not name:
        h=soup.find("h1")
        if h: name=h.get_text(" ",strip=True)
    if not name:
        # Find the first line after the NO line that isn't a generic title.
        for i,line in enumerate(lines[:40]):
            if re.fullmatch(r"NO\.\s*\d+",line,re.I) and i+1<len(lines):
                name=lines[i+1]; break

    # Hero image: prefer og:image, then an image whose alt/src mentions the name.
    image=None
    meta=soup.find("meta",property="og:image")
    if meta and meta.get("content"): image=urljoin(url,meta["content"])
    if not image and name:
        for im in soup.find_all("img"):
            alt=(im.get("alt") or "").lower()
            src=im.get("src") or im.get("data-src") or ""
            if name.lower() in alt and src:
                image=urljoin(url,src); break

    # Secondary portrait fallback: Aniidex often exposes a round portrait in og:image.
    if not image and name:
        try:
            secondary = urljoin(ANIIDEX, slug(name) + "/")
            r2 = requests.get(secondary, headers=HEADERS, timeout=20)
            if r2.ok:
                s2 = BeautifulSoup(r2.text, "html.parser")
                m2 = s2.find("meta", property="og:image")
                if m2 and m2.get("content"):
                    image = urljoin(secondary, m2["content"])
        except Exception:
            pass

    # Header facts are before "Attributes".
    header=lines[:lines.index("Attributes：")] if "Attributes：" in lines else lines[:40]
    elements=[]
    for line in header:
        el=canonical_element(line)
        if el and el not in elements: elements.append(el)
    roles=[line.upper() for line in header if line.upper() in ROLES]
    role_out=[]
    for r in roles:
        if r=="BREAK": r="Break"
        if r=="REGEN": r="Regen"
        if r not in role_out: role_out.append(r)

    # Stats.
    joined="\n".join(lines)
    stats={}
    for key in STAT_KEYS:
        m=re.search(re.escape(key)+r"\s*:\s*(\d+(?:\.\d+)?)",joined,re.I)
        if m: stats[key]=float(m.group(1)) if "." in m.group(1) else int(m.group(1))

    # Forms are presented together near the top of current official pages.
    forms=[]
    if "Basic Form" in lines:
        start=lines.index("Basic Form")
        for line in lines[start:start+12]:
            if "Form" in line and len(line)<60:
                # split concatenated forms such as Basic FormForest Form
                for f in re.findall(r"[A-Z][A-Za-z ]+Form",line):
                    if f not in forms: forms.append(f)

    # Trait.
    trait=None
    if "Trait" in lines:
        idx=lines.index("Trait")
        chunk=lines[idx+1:idx+5]
        if chunk:
            trait={"name":chunk[0],"description":" ".join(chunk[1:])}

    # Skills. The official rendered text follows:
    # Skill Name -> Description -> Element: -> Type/Cost/Power.
    skills=[]
    if "Skill Details" in lines:
        start=lines.index("Skill Details")+1
        end=lines.index("TOP") if "TOP" in lines[start:] else len(lines)
        s=lines[start:end]
        i=0
        while i<len(s):
            if i+4<len(s) and s[i+2]=="Element:":
                name2=s[i]
                desc=s[i+1]
                typ=re.sub(r"^Type:\s*","",s[i+3],flags=re.I)
                cost=re.sub(r"^Cost:\s*","",s[i+4],flags=re.I)
                power=""
                if i+5<len(s) and s[i+5].lower().startswith("power:"):
                    power=re.sub(r"^Power:\s*","",s[i+5],flags=re.I)
                    i+=6
                else:
                    i+=5
                skills.append({"name":name2,"description":desc,"type":typ,"cost":cost,"power":power})
            else:
                i+=1

    all_text=" ".join(lines)
    return {
      "id": number,
      "name": name or fallback_name or "Unknown",
      "number": f"{int(number):03d}" if number and int(number)<1000 else str(number or fallback_number or ""),
      "sourceUrl": url,
      "imageUrl": image,
      "elements": elements,
      "roles": role_out,
      "stats": stats,
      "forms": forms,
      "trait": trait,
      "skills": skills,
      "analysis": {"tags":tags_for(all_text),"notes":[]},
      "lastVerified": time.strftime("%Y-%m-%d")
    }

def slug(name):
    return re.sub(r"[^a-z0-9]+","-",name.lower()).strip("-")

def main():
    print("Downloading official index...")
    soup=BeautifulSoup(get(INDEX_URL),"html.parser")
    links=[]
    seen=set()
    for a in soup.find_all("a",href=True):
        href=urljoin(INDEX_URL,a["href"])
        txt=a.get_text(" ",strip=True)
        if "/item/" in urlparse(href).path and href not in seen:
            seen.add(href)
            m=re.search(r"NO\.\s*(\d+)",txt,re.I)
            # The official index link text contains the number and name.
            nm=re.sub(r"^NO\.\s*\d+\s*","",txt,flags=re.I).strip()
            if nm:
                links.append((href,nm,int(m.group(1)) if m else None))

    # Deduplicate by number/name, preferring the first link (Basic Form).
    by_key={}
    for u,nm,num in links:
        key=(num or 0,nm.lower())
        by_key[key]=(u,nm,num)

    print(f"Found {len(by_key)} official item links.")
    output=[]
    for idx,(u,nm,num) in enumerate(by_key.values(),1):
        try:
            print(f"[{idx}/{len(by_key)}] {nm}")
            output.append(parse_item(u,nm,num))
        except Exception as e:
            print("  ERROR:",e)
            output.append({
              "id":num,"name":nm,"number":f"{int(num):03d}" if num and int(num)<1000 else str(num or ""),
              "sourceUrl":u,"imageUrl":None,"elements":[],"roles":[],"stats":{},"forms":[],
              "trait":None,"skills":[],"analysis":{"tags":[],"notes":[f"Refresh error: {e}"]},
              "lastVerified":time.strftime("%Y-%m-%d")
            })
        time.sleep(0.12)

    output.sort(key=lambda x:int(x.get("id") or 99999))
    OUT.write_text(json.dumps(output,ensure_ascii=False,indent=2),encoding="utf-8")
    print("Wrote",OUT)

if __name__=="__main__":
    main()
